name: Continuous Deployment (CD) to GitHub Pages

on:
  push:
    branches:
      - main  # 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (se necessário)
        run: |
          npm install

      - name: Build the project (se necessário)
        run: |
         
          echo 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./  
