name: Continuous Integration

on:
  push:
    branches:
      - main  # O workflow será executado em pushes na branch 'main'
  pull_request:
    branches:
      - main  # O workflow também será executado em pull requests para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # A execução ocorrerá em um ambiente Ubuntu mais recente

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Configura o Node.js no ambiente
        with:
          node-version: '14'  # Versão do Node.js

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run tests
        run: npm test  # Executa os testes do projeto
